## Capture-recapture data {#dataCMR}

```{r globalGetDataCMR, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r librariesDataCMR, echo = FALSE}
library(getWBData)
library(tidyverse)
library(lubridate)
library(validate)
```

### Get data
West Brook electrofishing data formatted for Capture-Mark-Recapture analysis for tagged individuals
```{r CMR}

if(getNew_cdWB_CMR0) {
  cdWB_CMR0 <- 
    createCoreData(
      sampleType = "electrofishing", #"stationaryAntenna","portableAntenna"),
      whichDrainage = "west",
      columnsToAdd =
        c("sampleNumber",
          "river",
          "riverMeter",
          "survey",
          "pass",
          'observedLength',
          'observedWeight')
    ) %>%
    addTagProperties(
      columnsToAdd = 
        c("cohort",
          "species",
          "dateEmigrated",
          "sex",
          "species")
      ) %>%
    dplyr::filter(!is.na(tag), 
                  area %in% c("trib","inside","below","above"), 
                  !is.na(sampleNumber) 
                  ) %>%
    createCmrData(maxAgeInSamples = 20, 
                  inside = F, 
                  censorDead = F, 
                  censorEmigrated = T) %>%
    addSampleProperties() %>%
    addEnvironmental() %>%
    addKnownZ() %>%
    fillSizeLocation(size = F) #assumes fish stay in same location until observed elsewhere

  save(cdWB_CMR0, file = './data/cdWB_CMR0.RData')
  
} else {
  load(file = './data/cdWB_CMR0.RData')
}
str(cdWB_CMR0)
```

### Make encounter history file
```{r enc hist}

ehAll0 <- cdWB_CMR0 %>%
  arrange(sampleNumber, tag) %>%
  pivot_wider( 
    id_cols = tag, 
    names_from = sampleNumber, 
    names_prefix = "s",
    values_from = enc, 
    values_fill = 0
  )


getEH <- function(d, f){ 

  encs <- d %>%
    filter(eval(f)) %>%
    arrange(sampleNumber, tag) %>%
    pivot_wider( 
      id_cols = tag, 
      names_from = sampleNumber, 
      names_prefix = "s",
      values_from = enc, 
      values_fill = 0
  )
  
  return
  encs %>%
    unite(
      all, 
      sep = "") %>%
    mutate(tag = substr(all, 1, 10),
           encHistory = substr(all, 11, nchar(all)))
}

# all fish
save(getEH(cdWB_CMR0, TRUE), file = './data/ehAll.RData')

spp <- expression(species %in% c("bkt", "bnt"))
ehSpp <- getEH(cdWB_CMR0, spp)
save(ehSpp, file = './data/ehBKTBNT.RData')


```


### Wrangle data



### Explore data
```{r}

ggplot(cdWB_CMR0 %>% filter(enc ==1), aes(year)) +
  geom_bar() +
  facet_grid(river + season ~ species)
  

```


