---
title: "Untitled"
author: "Ben Letcher"
date: "5/6/2021"
output: html_document
---

```{r}
# library(devtools)
# devtools::install_github('Conte-Ecology/westBrookData/getWBData')
library(getWBData)

# devtools::install_github('bletcher/getPrepareWBData')
library(getPrepareWBData) # this has functions for preparing West Brook data

```

West Brook electrofishing data, all salmonids (tagged and untagged)
```{r}
cdWB <- createCoreData(
      sampleType = "electrofishing",  #"stationaryAntenna","portableAntenna"
      columnsToAdd = c("sampleNumber",
                       "river",
                       "survey",
                       "observedLength",
                       "observedWeight"),
      includeUntagged = TRUE,
      whichDrainage = "west"
    ) %>%
    addTagProperties(
      columnsToAdd = c("cohort",
                       "species",
                       "dateEmigrated",
                       "sex",
                       "species"
      )
    ) %>%
    dplyr::filter(species %in% c( "bkt","bnt","ats"),
                  area %in% c("trib","inside","below","above"),
                  !is.na(sampleNumber)) %>%
    addSampleProperties() %>%
    addEnvironmental()

```

West Brook electrofishing data with Capture-Mark-Recapture data added for tagged individuals
```{r}
  cdWB_CMR <- 
    createCoreData(
      sampleType = "electrofishing", #"stationaryAntenna","portableAntenna"),
      whichDrainage = "west",
      columnsToAdd =
        c("sampleNumber",
          "river",
          "riverMeter",
          "survey",
          'observedLength',
          'observedWeight')
    ) %>%
    addTagProperties(
      columnsToAdd = 
        c("cohort",
          "species",
          "dateEmigrated",
          "sex",
          "species")
      ) %>%
    dplyr::filter(!is.na(tag), 
                  area %in% c("trib","inside","below","above"), 
                  !is.na(sampleNumber) 
                  ) %>%
    createCmrData(maxAgeInSamples = 20, 
                  inside = F, 
                  censorDead = F, 
                  censorEmigrated = T) %>%
    addSampleProperties() %>%
    addEnvironmental() %>%
    addKnownZ() %>%
    fillSizeLocation(size = F) #assumes fish stay in same location until observed elsewhere
```

West Brook wanding data, all salmonids (tagged)
```{r}
# from wandingDataWB project in d:/ben/github/wandingData/
cdWB_Wanding <- createCoreData(
  sampleType = "portableAntenna",
  columnsToAdd = c("tag", 
                   "detectionDate", 
                   "river", 
                   "area", 
                   "section", 
                   "survey", 
                   "sampleName", 
                   "readerId", 
                   "aliveOrDead", 
                   "instance", 
                   "pass", 
                   "quarter", 
                   "leftOrRight", 
                   "habitat", 
                   "cover", 
                   "justification", 
                   "comment")
  ) %>% 
  addTagProperties() %>%
  dplyr::filter( species %in% c( "bkt","bnt","ats" ) )
```



```{r}
#conDplyr to show tables

# default values for createCoreData()
# function (sampleType = "electrofishing", baseColumns = T, 
#    columnsToAdd = NULL, includeUntagged = F, whichDrainage = "west") 

cd <- getCoreData("west")
```
